<a href="https://colab.research.google.com/github/pachterlab/Bi-BE-CS-183-2022/blob/main/HW1/Problem2_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bi/Be/Cs 183 2021-2022: Intro to Computational Biology
TAs: Meichen Fang, Tara Chari, Zitong (Jerry) Wang

**Submit your notebooks by sharing a clickable link with Viewer access. Link must be accessible from submitted assignment document.**

Make sure Runtime $\rightarrow$ Restart and run all works without error

In [1]:
# This is  used to time the running of the notebook
import time
start_time = time.time()

# **Problem 2**


In [2]:
#import packages
import numpy as np

In [3]:
#gene expression matrix
G = np.array([[1,2,3,3],[3,1,9,4],[1,4,3,5]])

## (c)

In [4]:
r = np.linalg.matrix_rank(G)
print("The rank of G is ", r)

The rank of G is  2


## (e)

### (i)

$L_1$ distance

In [5]:
D=np.zeros((3,3))
for i,c in enumerate(G):
  for j in range(i+1,len(G)):
    D[i,j]=np.sum(np.abs(G[i]-G[j]))
    D[j,i]=D[i,j]
D

array([[ 0., 10.,  4.],
       [10.,  0., 12.],
       [ 4., 12.,  0.]])

$L_2$ distance

In [6]:
D=np.zeros((3,3))
for i,c in enumerate(G):
  for j in range(i+1,len(G)):
    D[i,j]=np.sqrt(np.sum((G[i]-G[j])**2))
    D[j,i]=D[i,j]
D

array([[0.        , 6.4807407 , 2.82842712],
       [6.4807407 , 0.        , 7.07106781],
       [2.82842712, 7.07106781, 0.        ]])

cosine similarity

In [7]:
g=G/np.sqrt(np.sum(G**2,axis=1)).reshape(3,-1)
D=g@np.transpose(g)
D

array([[1.        , 0.88694537, 0.96352932],
       [0.88694537, 1.        , 0.730999  ],
       [0.96352932, 0.730999  , 1.        ]])

### (iii)

In [8]:
#gene expression matrix
G = np.array([[1,2,3,3],[3,1,9,4],[1,4,3,5]])+1

In [9]:
g=G/np.sqrt(np.sum(G**2,axis=1)).reshape(3,-1)
D=g@np.transpose(g)
D

array([[1.        , 0.916097  , 0.97724452],
       [0.916097  , 1.        , 0.81200025],
       [0.97724452, 0.81200025, 1.        ]])

In [10]:
# Running time of the notebook
print("{:.2f} minutes".format((time.time()-start_time)/60))

0.00 minutes
